import sharp from "sharp";
import { sanitizeFileName } from "../../shared/naming.js";
import { pxToCm } from "../../shared/units.js";
import { fullPlanReconstructionOk, validateRasterSource } from "./jobService.js";
import { escapeXml } from "./svgService.js";

export async function generateSewingMap(job, { dialog, resolveOutputPath, previewProvider }) {
  if (!fullPlanReconstructionOk(job)) throw new Error("O mapa não pode ser gerado porque a reconstrução matemática do plano falhou.");
  let dpi = Number(job.source.dpi), thumb, info;
  if (job.source.engine === "pdf") { thumb = await previewProvider(job.source.filePath, job.source.pageNumber || 1, 1380, 820); info = await sharp(thumb).metadata(); }
  else { ({ dpi } = await validateRasterSource(job)); const rendered = await sharp(job.source.filePath, { limitInputPixels: false }).resize({ width: 1380, height: 820, fit: "inside", withoutEnlargement: false }).png().toBuffer({ resolveWithObject: true }); thumb = rendered.data; info = rendered.info; }
  const pageWidth = 1800, imageX = Math.round((pageWidth - info.width) / 2), imageY = 250, listTop = imageY + info.height + 150, rowHeight = 54, pageHeight = Math.max(1350, listTop + job.slices.length * rowHeight + 180), lines = [], labels = [];
  for (let i = 0; i < job.slices.length - 1; i += 1) { const slice = job.slices[i]; if (job.orientation === "horizontal") { const y = imageY + (slice.endPx / job.source.heightPx) * info.height; lines.push(`<line x1="${imageX}" y1="${y.toFixed(2)}" x2="${imageX + info.width}" y2="${y.toFixed(2)}" stroke="#d92d20" stroke-width="5" stroke-dasharray="18 12"/>`); const seam = slice.seam?.labels?.after; if (seam) labels.push(`<text x="${imageX + 16}" y="${y - 12}" font-size="30" font-weight="800" fill="#101828">${escapeXml(seam[0])}</text><text x="${imageX + info.width - 16}" y="${y - 12}" text-anchor="end" font-size="30" font-weight="800" fill="#101828">${escapeXml(seam[1])}</text>`); } else { const x = imageX + (slice.endPx / job.source.widthPx) * info.width; lines.push(`<line x1="${x.toFixed(2)}" y1="${imageY}" x2="${x.toFixed(2)}" y2="${imageY + info.height}" stroke="#d92d20" stroke-width="5" stroke-dasharray="18 12"/>`); const seam = slice.seam?.labels?.after; if (seam) labels.push(`<text x="${x + 12}" y="${imageY + 34}" font-size="30" font-weight="800" fill="#101828">${escapeXml(seam[0])}</text><text x="${x + 12}" y="${imageY + info.height - 18}" font-size="30" font-weight="800" fill="#101828">${escapeXml(seam[1])}</text>`); } }
  const sliceRows = job.slices.map((slice, i) => { const y = listTop + i * rowHeight, before = slice.seam?.labels?.before?.join("/") || "—", after = slice.seam?.labels?.after?.join("/") || "—", usefulCm = pxToCm(slice.usefulPx, dpi).toFixed(2).replace(".", ","), finalCm = Number(slice.finalLimitedAxisCm || 0).toFixed(2).replace(".", ","); return `<rect x="150" y="${y - 34}" width="1500" height="46" rx="8" fill="${i % 2 ? "#f2f4f7" : "#ffffff"}"/><text x="175" y="${y}" font-size="26" font-weight="800" fill="#101828">FAIXA ${slice.index}/${job.slices.length}</text><text x="480" y="${y}" font-size="23" fill="#344054">ÚTIL ${usefulCm} CM</text><text x="760" y="${y}" font-size="23" fill="#344054">FINAL ${finalCm} CM</text><text x="1080" y="${y}" font-size="23" fill="#344054">ANTES ${escapeXml(before)}</text><text x="1370" y="${y}" font-size="23" fill="#344054">DEPOIS ${escapeXml(after)}</text>`; }).join("");
  const svg = `<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="${pageWidth}" height="${pageHeight}"><rect width="100%" height="100%" fill="#ffffff"/><text x="120" y="88" font-size="52" font-family="Arial" font-weight="900" fill="#101828">MAPA DE COSTURA</text><text x="120" y="138" font-size="27" font-family="Arial" fill="#344054">${escapeXml(String(job.baseName || "ARTE").toUpperCase())}</text><text x="120" y="182" font-size="24" font-family="Arial" fill="#475467">TECIDO: ${escapeXml(job.fabric?.name || "")} · LIMITE: ${escapeXml(String(job.fabric.maxPrintableWidthCm).replace(".", ","))} CM · ORIENTAÇÃO: ${job.orientation === "horizontal" ? "HORIZONTAL" : "VERTICAL"} · ${job.slices.length} FAIXA(S)</text><image x="${imageX}" y="${imageY}" width="${info.width}" height="${info.height}" xlink:href="data:image/png;base64,${thumb.toString("base64")}"/><rect x="${imageX}" y="${imageY}" width="${info.width}" height="${info.height}" fill="none" stroke="#101828" stroke-width="4"/>${lines.join("")}${labels.join("")}<text x="150" y="${listTop - 70}" font-size="31" font-family="Arial" font-weight="800" fill="#101828">ORDEM E EMENDAS</text>${sliceRows}<text x="150" y="${pageHeight - 70}" font-size="20" font-family="Arial" fill="#667085">AUTOCUT · ${job.source.engine === "pdf" ? "PDF VETORIAL" : `DPI ORIGINAL ${dpi}`} · mesmas posições de corte do projeto</text></svg>`;
  const baseName = `${sanitizeFileName(job.baseName || "ARTE")}_MAPA_DE_COSTURA`;
  const outputPath = await resolveOutputPath({ dialog, folder: job.outputDirectory, baseName, extension: "jpg", policy: job.output?.conflict || "version" });
  if (!outputPath) return { ok: false, skipped: true, filePath: null };
  await sharp(Buffer.from(svg)).flatten({ background: "#ffffff" }).jpeg({ quality: 94, chromaSubsampling: "4:4:4" }).withMetadata({ density: 150 }).toFile(outputPath);
  const saved = await sharp(outputPath).metadata();
  return { ok: Boolean(saved.width === pageWidth && saved.height === pageHeight), filePath: outputPath, widthPx: saved.width, heightPx: saved.height, slices: job.slices.length };
}
