export const PHOTOSHOP_RUNNER_VBS = `Option Explicit
On Error Resume Next
Dim appRef, jsxPath, jobPath, resultPath
jsxPath = WScript.Arguments(0)
jobPath = WScript.Arguments(1)
resultPath = WScript.Arguments(2)
Set appRef = CreateObject("Photoshop.Application")
If Err.Number <> 0 Then
  WScript.Echo "PHOTOSHOP_COM_ERROR:" & Err.Description
  WScript.Quit 31
End If
Err.Clear
appRef.BringToFront
Call appRef.DoJavaScriptFile(jsxPath, Array(jobPath, resultPath), 1)
If Err.Number <> 0 Then
  WScript.Echo "PHOTOSHOP_SCRIPT_ERROR:" & Err.Description
  WScript.Quit 32
End If
WScript.Quit 0
`;

export const PHOTOSHOP_EXPORT_JSX = String.raw`#target photoshop
app.displayDialogs = DialogModes.NO;
(function () {
  var jobPath=arguments[0],resultPath=arguments[1],oldRuler=app.preferences.rulerUnits,oldType=app.preferences.typeUnits,source=null,results=[];
  function readJson(filePath){var f=File(filePath);if(!f.open("r"))throw new Error("Não foi possível ler job JSON.");var t=f.read();f.close();return JSON.parse(t);}
  function writeJson(filePath,data){var f=File(filePath);f.encoding="UTF8";if(!f.open("w"))throw new Error("Não foi possível gravar resultado JSON.");f.write(JSON.stringify(data));f.close();}
  function px(v){return UnitValue(Math.round(v),"px");} function pt(v){return UnitValue(v,"pt");}
  function hexColor(hex){var h=String(hex||"#ffffff").replace("#","");if(!/^[0-9a-fA-F]{6}$/.test(h))h="ffffff";var c=new SolidColor();c.rgb.red=parseInt(h.substr(0,2),16);c.rgb.green=parseInt(h.substr(2,2),16);c.rgb.blue=parseInt(h.substr(4,2),16);return c;}
  function resizeMargins(doc,m){if(m.topPx>0)doc.resizeCanvas(doc.width,px(doc.height.as("px")+m.topPx),AnchorPosition.BOTTOMCENTER);if(m.bottomPx>0)doc.resizeCanvas(doc.width,px(doc.height.as("px")+m.bottomPx),AnchorPosition.TOPCENTER);if(m.leftPx>0)doc.resizeCanvas(px(doc.width.as("px")+m.leftPx),doc.height,AnchorPosition.MIDDLERIGHT);if(m.rightPx>0)doc.resizeCanvas(px(doc.width.as("px")+m.rightPx),doc.height,AnchorPosition.MIDDLELEFT);}
  function fillMargins(doc,m,margin){if(margin.transparent)return;var w=doc.width.as("px"),h=doc.height.as("px"),layer=doc.artLayers.add();layer.name="AUTOCUT_MARGENS";layer.opacity=Math.max(0,Math.min(100,Number(margin.opacity==null?1:margin.opacity)*100));var color=hexColor(margin.color||"#ffffff");function fillRect(a,b,c,d){if(c<=a||d<=b)return;doc.selection.select([[a,b],[c,b],[c,d],[a,d]]);doc.selection.fill(color,ColorBlendMode.NORMAL,100,false);doc.selection.deselect();}fillRect(0,0,w,m.topPx);fillRect(0,h-m.bottomPx,w,h);fillRect(0,m.topPx,m.leftPx,h-m.bottomPx);fillRect(w-m.rightPx,m.topPx,w,h-m.bottomPx);try{layer.move(doc.layers[doc.layers.length-1],ElementPlacement.PLACEAFTER);}catch(e){}}
  function addText(doc,name,value,x,y,sizePt,colorHex,font,justification,rotation){if(!value)return;var layer=doc.artLayers.add();layer.name=name;layer.kind=LayerKind.TEXT;var t=layer.textItem;t.contents=value;t.size=pt(Math.max(4,sizePt));t.color=hexColor(colorHex||"#111111");try{if(font)t.font=font;}catch(e){}t.justification=justification||Justification.LEFT;t.position=[px(x),px(y)];if(rotation)layer.rotate(rotation,AnchorPosition.MIDDLECENTER);}
  function fitSizePt(requestedPt,marginPx,dpi){var marginPt=marginPx/dpi*72;return Math.max(4,Math.min(requestedPt,marginPt*.72));}
  function technicalText(doc,slice,job,m){var dpi=job.source.dpi,w=doc.width.as("px"),h=doc.height.as("px"),ident=job.identification||{},edgePx=Math.max(1,(Number(ident.edgeDistanceCm)||.18)/2.54*dpi),requestedPt=Math.max(4,(Number(ident.sizeCm)||2)/2.54*72);if(ident.enabled){var before=slice.seam&&slice.seam.labels?slice.seam.labels.before:null,after=slice.seam&&slice.seam.labels?slice.seam.labels.after:null;if(job.orientation==="horizontal"){if(before&&m.topPx>0){var st=fitSizePt(requestedPt,m.topPx,dpi);addText(doc,"AUTOCUT_"+before[0],before[0],m.leftPx+edgePx,m.topPx*.60,st,ident.color,ident.font,Justification.LEFT,0);addText(doc,"AUTOCUT_"+before[1],before[1],w-m.rightPx-edgePx,m.topPx*.60,st,ident.color,ident.font,Justification.RIGHT,0);}if(after&&m.bottomPx>0){var sb=fitSizePt(requestedPt,m.bottomPx,dpi);addText(doc,"AUTOCUT_"+after[0],after[0],m.leftPx+edgePx,h-m.bottomPx*.40,sb,ident.color,ident.font,Justification.LEFT,0);addText(doc,"AUTOCUT_"+after[1],after[1],w-m.rightPx-edgePx,h-m.bottomPx*.40,sb,ident.color,ident.font,Justification.RIGHT,0);}}else{if(before&&m.leftPx>0){var sl=fitSizePt(requestedPt,m.leftPx,dpi);addText(doc,"AUTOCUT_"+before[0],before[0],m.leftPx*.55,m.topPx+edgePx+sl*dpi/72,sl,ident.color,ident.font,Justification.CENTER,-90);addText(doc,"AUTOCUT_"+before[1],before[1],m.leftPx*.55,h-m.bottomPx-edgePx-sl*dpi/72,sl,ident.color,ident.font,Justification.CENTER,-90);}if(after&&m.rightPx>0){var sr=fitSizePt(requestedPt,m.rightPx,dpi);addText(doc,"AUTOCUT_"+after[0],after[0],w-m.rightPx*.45,m.topPx+edgePx+sr*dpi/72,sr,ident.color,ident.font,Justification.CENTER,90);addText(doc,"AUTOCUT_"+after[1],after[1],w-m.rightPx*.45,h-m.bottomPx-edgePx-sr*dpi/72,sr,ident.color,ident.font,Justification.CENTER,90);}}}var artName=String(job.baseName||"").toUpperCase(),ns=job.nameSides||{};if(artName){var np=requestedPt*.55;if(ns.top&&m.topPx>0)addText(doc,"AUTOCUT_NOME_TOP",artName,w/2,m.topPx*.60,fitSizePt(np,m.topPx,dpi),ident.color,ident.font,Justification.CENTER,0);if(ns.bottom&&m.bottomPx>0)addText(doc,"AUTOCUT_NOME_BOTTOM",artName,w/2,h-m.bottomPx*.40,fitSizePt(np,m.bottomPx,dpi),ident.color,ident.font,Justification.CENTER,0);if(ns.left&&m.leftPx>0)addText(doc,"AUTOCUT_NOME_LEFT",artName,m.leftPx*.55,h/2,fitSizePt(np,m.leftPx,dpi),ident.color,ident.font,Justification.CENTER,-90);if(ns.right&&m.rightPx>0)addText(doc,"AUTOCUT_NOME_RIGHT",artName,w-m.rightPx*.45,h/2,fitSizePt(np,m.rightPx,dpi),ident.color,ident.font,Justification.CENTER,90);}}
  function savePsd(doc,filePath){var o=new PhotoshopSaveOptions();o.alphaChannels=true;o.annotations=false;o.embedColorProfile=true;o.layers=true;o.spotColors=true;doc.saveAs(File(filePath),o,true,Extension.LOWERCASE);}
  function savePsb(doc,filePath){var d1=new ActionDescriptor(),d2=new ActionDescriptor();d2.putBoolean(stringIDToTypeID("maximizeCompatibility"),true);d1.putObject(stringIDToTypeID("as"),stringIDToTypeID("largeDocumentFormat"),d2);d1.putPath(stringIDToTypeID("in"),File(filePath));d1.putBoolean(stringIDToTypeID("copy"),true);executeAction(stringIDToTypeID("save"),d1,DialogModes.NO);}
  try{app.preferences.rulerUnits=Units.PIXELS;app.preferences.typeUnits=TypeUnits.POINTS;var job=readJson(jobPath);source=app.open(File(job.source.filePath));if(Math.round(source.width.as("px"))!==Math.round(job.source.widthPx)||Math.round(source.height.as("px"))!==Math.round(job.source.heightPx))throw new Error("A origem mudou desde o cálculo.");if(Math.abs(source.resolution-Number(job.source.dpi))>.05)throw new Error("O DPI da origem mudou desde o cálculo.");for(var i=0;i<job.tasks.length;i++){var task=job.tasks[i],slice=task.slice,doc=source.duplicate();app.activeDocument=doc;if(job.orientation==="horizontal")doc.crop([px(0),px(slice.startPx),px(job.source.widthPx),px(slice.endPx)]);else doc.crop([px(slice.startPx),px(0),px(slice.endPx),px(job.source.heightPx)]);resizeMargins(doc,job.margins);fillMargins(doc,job.margins,job.margin||{});technicalText(doc,slice,job,job.margins);if(task.format==="PSB")savePsb(doc,task.outputPath);else savePsd(doc,task.outputPath);doc.close(SaveOptions.DONOTSAVECHANGES);var check=app.open(File(task.outputPath));results.push({index:slice.index,filePath:task.outputPath,widthPx:Math.round(check.width.as("px")),heightPx:Math.round(check.height.as("px")),dpi:check.resolution,layerCount:check.layers.length});check.close(SaveOptions.DONOTSAVECHANGES);}source.close(SaveOptions.DONOTSAVECHANGES);source=null;writeJson(resultPath,{ok:true,results:results});}catch(err){try{if(source)source.close(SaveOptions.DONOTSAVECHANGES);}catch(e2){}writeJson(resultPath,{ok:false,error:String(err),line:err.line||null,results:results});}finally{app.preferences.rulerUnits=oldRuler;app.preferences.typeUnits=oldType;}
})();`;
