import fs from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { execFile } from "node:child_process";
import { promisify } from "node:util";
import { baseNameFromPath } from "../../shared/naming.js";
const execFileAsync=promisify(execFile);
const RUNNER=`Option Explicit\nOn Error Resume Next\nDim appRef, jsxPath, sourcePath, resultPath, previewPath\njsxPath=WScript.Arguments(0)\nsourcePath=WScript.Arguments(1)\nresultPath=WScript.Arguments(2)\npreviewPath=WScript.Arguments(3)\nSet appRef=CreateObject("Photoshop.Application")\nIf Err.Number<>0 Then WScript.Echo "PHOTOSHOP_COM_ERROR:" & Err.Description: WScript.Quit 31\nErr.Clear\nappRef.BringToFront\nCall appRef.DoJavaScriptFile(jsxPath,Array(sourcePath,resultPath,previewPath),1)\nIf Err.Number<>0 Then WScript.Echo "PHOTOSHOP_SCRIPT_ERROR:" & Err.Description: WScript.Quit 32\nWScript.Quit 0\n`;
const INSPECT_JSX=String.raw`#target photoshop
app.displayDialogs=DialogModes.NO;(function(){var sourcePath=arguments[0],resultPath=arguments[1],previewPath=arguments[2],oldRuler=app.preferences.rulerUnits,doc=null;function writeJson(p,d){var f=File(p);f.encoding="UTF8";if(!f.open("w"))throw new Error("Não foi possível gravar inspeção.");f.write(JSON.stringify(d));f.close();}try{app.preferences.rulerUnits=Units.PIXELS;doc=app.open(File(sourcePath));var w=Math.round(doc.width.as("px")),h=Math.round(doc.height.as("px")),dpi=doc.resolution,profile="";try{profile=doc.colorProfileName;}catch(e){}var dup=doc.duplicate();dup.flatten();var ratio=Math.min(1800/w,1200/h,1);if(ratio<1)dup.resizeImage(UnitValue(Math.max(1,Math.round(w*ratio)),"px"),UnitValue(Math.max(1,Math.round(h*ratio)),"px"),null,ResampleMethod.BICUBIC);var opt=new PNGSaveOptions();dup.saveAs(File(previewPath),opt,true,Extension.LOWERCASE);dup.close(SaveOptions.DONOTSAVECHANGES);writeJson(resultPath,{ok:true,widthPx:w,heightPx:h,dpi:dpi,layerCount:doc.layers.length,profile:profile,mode:String(doc.mode)});doc.close(SaveOptions.DONOTSAVECHANGES);doc=null;}catch(err){try{if(doc)doc.close(SaveOptions.DONOTSAVECHANGES);}catch(e2){}writeJson(resultPath,{ok:false,error:String(err),line:err.line||null});}finally{app.preferences.rulerUnits=oldRuler;}})();`;
export async function inspectPhotoshopArtwork(filePath){if(process.platform!=="win32")return{ok:false,filePath,baseName:baseNameFromPath(filePath),error:"PSD/PSB requer Adobe Photoshop no Windows para inspeção sem rasterização silenciosa."};const temp=await fs.mkdtemp(path.join(os.tmpdir(),"autocut-ps-inspect-")),jsxPath=path.join(temp,"inspect.jsx"),vbsPath=path.join(temp,"run.vbs"),resultPath=path.join(temp,"result.json"),previewPath=path.join(temp,"preview.png");await Promise.all([fs.writeFile(jsxPath,INSPECT_JSX,"utf8"),fs.writeFile(vbsPath,RUNNER,"utf8")]);try{await execFileAsync("cscript.exe",["//nologo",vbsPath,jsxPath,filePath,resultPath,previewPath],{timeout:5*60*1000,windowsHide:true,maxBuffer:1024*1024});const r=JSON.parse(await fs.readFile(resultPath,"utf8"));if(!r.ok)throw new Error(r.error||"Falha no Photoshop.");const preview=await fs.readFile(previewPath);return{ok:true,engine:"photoshop",filePath,baseName:baseNameFromPath(filePath),widthPx:r.widthPx,heightPx:r.heightPx,dpi:r.dpi,dpiDetected:true,dpiSynthetic:false,widthCm:r.widthPx/r.dpi*2.54,heightCm:r.heightPx/r.dpi*2.54,format:path.extname(filePath).slice(1).toLowerCase(),hasAlpha:true,space:r.mode||"Photoshop",depth:"layered",channels:null,layerCount:r.layerCount,profile:r.profile,previewDataUrl:`data:image/png;base64,${preview.toString("base64")}`};}catch(error){const text=String(error?.stderr||error?.message||error);return{ok:false,filePath,baseName:baseNameFromPath(filePath),error:/PHOTOSHOP_COM_ERROR|cannot create object|ActiveX/i.test(text)?"Adobe Photoshop não foi encontrado ou a automação COM não está disponível.":`Falha ao inspecionar PSD/PSB: ${text}`};}finally{await fs.rm(temp,{recursive:true,force:true});}}
